name: 'Register'
description: 'Register a new component version in Mach Composer Cloud'
author: 'Lab Digital'
branding:
  color: 'green'
  icon: 'package'

inputs:
  component:
    description: 'The component'
    required: true
  organization:
    description: 'Key of the organization'
    required: true
  project:
    description: 'Key of the project'
    required: true
  args:
    required: false
    description: 'Extra arguments to pass to register-component-version'
  client_id:
    description: 'Mach Composer Cloud client id'
    required: true
  client_secret:
    description: 'Mach Composer Cloud client secret'
    required: true
  mach_composer_version:
    description: 'Mach Composer Cli version'
    required: false
    default: '2.9.3'

runs:
  using: 'composite'
  steps:
    - name: Install MACH composer
      uses: mach-composer/setup-mach-composer@3ca0bd4e2c0f08fefc803a36fcbba70e5ee00d67 # main
      with:
        version: ${{ inputs.mach_composer_version }}

    - name: Register new version
      shell: bash
      env:
        MCC_DEBUG: 1
        MCC_CLIENT_ID: ${{ inputs.client_id }}
        MCC_CLIENT_SECRET: ${{ inputs.client_secret }}
        INPUT_ORGANIZATION: ${{ inputs.organization }}
        INPUT_PROJECT: ${{ inputs.project }}
        INPUT_COMPONENT: ${{ inputs.component }}
        INPUT_ARGS: ${{ inputs.args }}
      run: |
        mach-composer cloud register-component-version \
          --organization "$INPUT_ORGANIZATION" \
          --project "$INPUT_PROJECT" \
          --auto "$INPUT_COMPONENT" \
          $INPUT_ARGS
