name: 'Register'
description: 'Register a new component version in Mach Composer Cloud'
author: 'Lab Digital'
branding:
  color: 'green'
  icon: 'package'

inputs:
  component:
    description: 'The component'
    required: true
  organization:
    description: 'Key of the organization'
    required: true
  project:
    description: 'Key of the project'
    required: true
  args:
    required: false
    description: 'Extra arguments to pass to register-component-version'
  client_id:
    description: 'Key of the project'
    required: true
  client_secret:
    description: 'The version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install MACH composer
      uses: mach-composer/setup-mach-composer@main
      with:
        version: 2.9.3

    - name: Register new version
      shell: bash
      env:
        MCC_CLIENT_ID: ${{ inputs.client_id }}
        MCC_CLIENT_SECRET: ${{ inputs.client_secret }}
      run: |
        mach-composer cloud register-component-version \
          --organization ${{ inputs.organization }} \
          --project ${{ inputs.project }} \
          --auto ${{ inputs.component }} \
          --dry-run \
          ${{ inputs.args }}
