name: Validations

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.type != 'pull_request'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Prepare release
      uses: labd/changie-release-action@v0.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-workflow: ''

